#!/usr/bin/env bash

# create tmux session and windows
tmux new-session -d -s gladiator-game-rs-dev
tmux rename-window -t gladiator-game-rs-dev:1 cargo
tmux new-window -n nvim
tmux new-window -n zsh

# for running cargo commands
tmux send-keys -t gladiator-game-rs-dev:cargo 'cd ~/repos/github/alphagergedan/gladiator-game-rs' Enter
tmux send-keys -t gladiator-game-rs-dev:cargo 'source ~/.zsh/modules/rust.sh' Enter
tmux send-keys -t gladiator-game-rs-dev:cargo 'which cargo' Enter

# code editing
tmux send-keys -t gladiator-game-rs-dev:nvim 'cd ~/repos/github/alphagergedan/gladiator-game-rs' Enter
tmux send-keys -t gladiator-game-rs-dev:nvim 'source ~/.zsh/modules/rust.sh' Enter
tmux send-keys -t gladiator-game-rs-dev:nvim 'clear' Enter
tmux send-keys -t gladiator-game-rs-dev:nvim 'nvim' Enter

# empty shell
tmux send-keys -t gladiator-game-rs-dev:zsh 'cd ~/repos/github/alphagergedan/gladiator-game-rs' Enter
tmux send-keys -t gladiator-game-rs-dev:zsh 'source ~/.zsh/modules/rust.sh' Enter
tmux send-keys -t gladiator-game-rs-dev:zsh 'clear' Enter
